name: Build and deploy Release

on:
  push:
    tags:
      - v*
env:
  IMAGE_NAME: mortgage-calculator-api

jobs:

  push:
    name: Push image to packages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |

          # setting image id
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # getting the correct version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo $VERSION | sed -e 's/^v//')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  deploy:
    
    name: Deploy Release to Heroku
    runs-on: ubuntu-latest
    needs: push 

    steps:

      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Download image from GitHub Packages
        run: |

          # getting the correct version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker pull docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:$VERSION

      - name: Logout from GitHub registry
        run: docker logout docker.pkg.github.com

      - name: Login into Heroku registry
        run: echo "${{ secrets.HEROKU_TOKEN }}" | docker login registry.heroku.com -u ${{ secrets.HEROKU_MAIL }} --password-stdin

      - name: Push image to Heroku registry
        run: | 

          # Get correct version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:$VERSION registry.heroku.com/secret-journey-21988/web
          docker push registry.heroku.com/secret-journey-21988/web

      - name: Deploy image in Heorku App
        run: heroku container:release web -a secret-journey-21988
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
