name: Publish latest image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: mortgage-calculator-api

jobs:

  push:
    name: Push image to packages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: | 

          #  setting application version
          BUILD_COMMIT=$(git rev-parse --short HEAD)

          docker build . --file Dockerfile --build-arg APP_VERSION=dev-$BUILD_COMMIT --tag $IMAGE_NAME

      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |

          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
           VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION