name: Publish latest image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: mortgage-calculator-api

jobs:

  push:
    name: Push image to packages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: | 

          #  setting application version
          BUILD_COMMIT=$(git rev-parse --short HEAD)

          docker build . --file Dockerfile --build-arg APP_VERSION=dev-$BUILD_COMMIT --tag $IMAGE_NAME

      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag $IMAGE_NAME docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:latest
          docker push docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:latest
  
  push-docker-hub:

    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    needs: push

    steps:

      - name: Log into GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Download image from GitHub Packages
        run: docker pull docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:latest

      - name: Logout from GitHub registry
        run: docker logout docker.pkg.github.com

      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u lealoureiro --password-stdin
      
      - name: Push image to Docker Hub
        run: | 
          docker tag docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:latest lealoureiro/$IMAGE_NAME:latest
          docker push lealoureiro/${IMAGE_NAME}:latest
      
      - name: Logout from Docker Hub
        run: docker logout
